<a href="https://colab.research.google.com/github/JardelSilva-86/PythonParaAnaliseDeDados/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

O pacote Numpy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos.

Mas em Numpy, as dimensões são chamadas de eixo. O número de eixos é classificado. Em termos mais simples, quando você tem mais de uma matriz unidimensional, então o conceito do eixo surge. 
Por exemplo, a matriz 2-D tem 2 eixos.

In [1]:
# importar a lib
import numpy as np

In [2]:
# versão
print( np.__version__)

1.21.6


In [4]:
# Criar uma matriz
array = np.array( [10, 20, 30, 40, 50] )
array

array([10, 20, 30, 40, 50])

In [5]:
# Tipo
type( array )

numpy.ndarray

In [7]:
# matriz com 2 dimensões
duas = np.array(
    [[10, 9, 8, 7, 6],
     [5, 4, 3, 2, 1]]
)

duas

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [10]:
tres = np.array([
    [15, 14, 13, 12, 11,],
    [10, 9, 8, 7, 6],
    [5, 4, 3, 2, 1]
                 
])

print( tres )

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [11]:
# Experimento de processamento
np.arange( 100 )

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
# Estressando o Numpy 

Estressando_NP = np.arange( 1000000 )

len( Estressando_NP )

1000000

In [16]:
# 1º teste
# %time - Serve para verificar o tempo de processamento
%time for loop in Estressando_NP: pass

CPU times: user 71.6 ms, sys: 263 µs, total: 71.8 ms
Wall time: 74.4 ms


In [17]:
Estressando_NP01 = np.arange( 5000000 )
Estressando_NP02 = np.arange( 10000000 )
Estressando_NP03 = np.arange( 50000000 )

print( len( Estressando_NP01 ), len( Estressando_NP02 ),len( Estressando_NP03 ),)

5000000 10000000 50000000


In [18]:
# 2º teste
%time for loop in Estressando_NP01: pass

CPU times: user 364 ms, sys: 3.36 ms, total: 368 ms
Wall time: 373 ms


In [19]:
# 3º teste
%time for loop in Estressando_NP02: pass

CPU times: user 718 ms, sys: 0 ns, total: 718 ms
Wall time: 725 ms


In [20]:
# 4º teste
%time for loop in Estressando_NP03: pass

CPU times: user 3.44 s, sys: 0 ns, total: 3.44 s
Wall time: 3.48 s
